# -*- coding: utf-8 -*-
"""ADA - Preliminary data processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bMOzkkCTHIiqE0et1V0VVnnFDrKoIksQ
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

Dane = pd.read_csv('/content/drive/MyDrive/WstepnePrzetwarzanie.csv')

Dane

Dane.isna()

Dane.isnull()

Dane.isnull().sum()

Dane2=Dane.dropna(axis=0)

Dane2

Dane2.isna()

Dane2.fillna(Dane.mode())

import matplotlib.pyplot as plt

plt.show()

Dane2.boxplot()

import scipy.stats as stats
from scipy import stats

Dane2['Wiek'] = stats.zscore(Dane2['Wiek'])
print(Dane2.head())

Dane2['Dochód'] = stats.zscore(Dane2['Dochód'])
print(Dane.head())

print(stats.zscore(Dane2['Wiek']))

print(stats.zscore(Dane2['Dochód']))

X=((Dane2.Dochód-min(Dane2.Dochód))/(max(Dane2.Dochód)-min(Dane2.Dochód)))

X